In [1]:
import torch

### @ 等于 matmul

In [2]:
a=torch.tensor([[1,2,3]])
b=torch.tensor([[5],[6],[7]])
a,b

(tensor([[1, 2, 3]]),
 tensor([[5],
         [6],
         [7]]))

In [3]:
torch.matmul(a,b) 

tensor([[38]])

In [4]:
a@b

tensor([[38]])